### ISSUE TITLE
Getting TypeError when updating hits certain shows

### ISSUE THREAD

**Issue by Berzerker** [RickDB/PlexAniSync#10]
```python
2019-10-13 17:37:03 [ANILIST] Plex series was not on your AniList list: Shinseiki Evangelion Gekijouban: The End of Evangelion
2019-10-13 17:37:03 [ANILIST] Searching best title / year match for: Shinseiki Evangelion Gekijouban: The End of Evangelion
2019-10-13 17:37:04 [ANILIST] Trying alternative title for search: shinseikievangeliongekijoubantheendofevangelion
Traceback (most recent call last):
  File "PlexAniSync.py", line 142, in <module>
    start()
  File "PlexAniSync.py", line 135, in start
    plex_series_watched)
  File "/home/berzerker/.plexanisync/anilist.py", line 549, in match_to_plex
    plex_title_clean_without_year, plex_year)
  File "/home/berzerker/.plexanisync/anilist.py", line 1035, in find_id_best_match
    if item[0].media:
TypeError: 'NoneType' object is not subscriptable
```

Let me know if you need any additional information

**Comment by RickDB** [comment]
Thanks for log output, certainly an odd one but will see if I can find t he cause.

**Comment by RickDB** [comment]
Add additional check which should fix this, it does mean AniList doesn't a valid result we can use though.
For OVA releases still need a better solution as it can be hit and miss right now.

**Comment by Berzerker** [comment]
Thanks, that seemed to work.
