### ISSUE TITLE
the custom mappings throws an error

### ISSUE THREAD

**Issue by user4302** [RickDB/PlexAniSync#108]
im using the custom mappings from here
https://github.com/RickDB/PlexAniSync-Custom-Mappings/blob/main/series-tvdb.en.yaml

i copied and pasted everything into 'custom_mappings.yaml'
and i get the following error when i run 'python PlexAniSync.py'

C:\Program Files\Plex\PlexAniSync>python PlexAniSync.py
2022-02-06 10:17:38 PlexAniSync - version: 1.3.16
2022-02-06 10:17:38 [MAPPING] Custom map file found: custom_mappings.yaml
Traceback (most recent call last):
  File "C:\Program Files\Plex\PlexAniSync\PlexAniSync.py", line 130, in <module>
    start()
  File "C:\Program Files\Plex\PlexAniSync\PlexAniSync.py", line 83, in start
    anilist.CUSTOM_MAPPINGS = read_custom_mappings()
  File "C:\Program Files\Plex\PlexAniSync\custom_mappings.py", line 32, in read_custom_mappings
    file_mappings = yamale.make_data(MAPPING_FILE, parser='ruamel')
  File "C:\Python310\lib\site-packages\yamale\yamale.py", line 29, in make_data
    raw_data = readers.parse_yaml(path, parser, content=content)
  File "C:\Python310\lib\site-packages\yamale\readers\yaml_reader.py", line 35, in parse_yaml
    return parse(f)
  File "C:\Python310\lib\site-packages\yamale\readers\yaml_reader.py", line 17, in _ruamel
    return list(yaml.load_all(f))
  File "C:\Python310\lib\site-packages\ruamel\yaml\main.py", line 460, in load_all
    while constructor.check_data():
  File "C:\Python310\lib\site-packages\ruamel\yaml\constructor.py", line 108, in check_data
    return self.composer.check_node()
  File "_ruamel_yaml.pyx", line 687, in _ruamel_yaml.CParser.check_node
  File "_ruamel_yaml.pyx", line 902, in _ruamel_yaml.CParser._parse_next_event
  File "_ruamel_yaml.pyx", line 911, in _ruamel_yaml.input_handler
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5624: character maps to <undefined>

C:\Program Files\Plex\PlexAniSync>

**Comment by KaiserBh** [comment]
Encoding issue, make sure the file is saved as UTF-8.

To confirm try downloading the .yaml file directly and use that.

**Comment by reconman** [comment]
Duplicate of #100. Sorry, forgot about that issue. Chūnibyō in the mapping is causing issues on Windows devices.

**Comment by KaiserBh** [comment]
> Duplicate of #100. Sorry, forgot about that issue. Chūnibyō in the mapping is causing issues on Windows devices.

Hmm haven't tried it on windows, but on my end linux seem to be fine.
