### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by dGstone18** [RickDB/PlexAniSync#130]
Got the sync working through the Unraid docker. Was messing around with custom mapping and started getting the following error/output after the same match every time after restarting the docker multiple times. Is this a rate limit issue?

`Traceback (most recent call last):
File "/plexanisync/PlexAniSync.py", line 130, in <module>
start()
File "/plexanisync/PlexAniSync.py", line 124, in start
anilist.match_to_plex(anilist_series, plex_series_watched)
File "/plexanisync/anilist.py", line 363, in match_to_plex
add_or_update_show_by_id(anilist_series, plex_title, plex_year, True, watchcount, anime_id)
File "/plexanisync/anilist.py", line 623, in add_or_update_show_by_id
add_by_id(
File "/plexanisync/anilist.py", line 635, in add_by_id
media_lookup_result = search_by_id(anilist_id)
File "/plexanisync/graphql.py", line 45, in search_by_id
response = send_graphql_request(query, variables)
File "/plexanisync/graphql.py", line 173, in send_graphql_request
response.raise_for_status()
File "/root/.local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graphql.anilist.co/`

**Comment by dGstone18** [comment]
Disregard this. Due to an incorrect title ID.
