### ISSUE TITLE
ImportError regarding dataclass_transform

### ISSUE THREAD

**Issue by DJScias** [RickDB/PlexAniSync#154]
Hello there,

As of the latest few updates on the `master` branch, it seems the script does no longer work through the [tautulli-plexanisync docker package](https://github.com/RickDB/PlexAniSync/pkgs/container/tautulli-plexanisync).

Every time the script runs, it errors with the following:
```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/plexanisync/TautulliSyncHelper.py", line 9, in <module>
            import anilist
        File "/plexanisync/anilist.py", line 7, in <module>
            import inflect
        File "/root/.local/lib/python3.9/site-packages/inflect/__init__.py", line 76, in <module>
            from pydantic import Field, validate_arguments
        File "pydantic/__init__.py", line 2, in init pydantic.__init__
        File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
            # +--- init= parameter
    ImportError: cannot import name dataclass_transform
```

This is after the DEBUG of:
```
Tautulli Notifiers :: Full script is: ['/usr/local/bin/python', '/plexanisync/TautulliSyncHelper.py', 'Tate no Yuusha no Nariagari']
```

I have re-pulled and re-created the docker container multiple times and so far no dice.

If more information is required, please do let me know.

**Comment by reconman** [comment]
Can you test the image ghcr.io/rickdb/tautulli-plexanisync:154-import-error?

I can only test it later.

**Comment by DJScias** [comment]
Hello there,

Ran a docker container with that build and got the following error:
```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/plexanisync/TautulliSyncHelper.py", line 9, in <module>
            import anilist
        File "/plexanisync/anilist.py", line 7, in <module>
            import inflect
        File "/usr/local/lib/python3.9/site-packages/inflect/__init__.py", line 76, in <module>
            from pydantic import Field, validate_arguments
        File "pydantic/__init__.py", line 2, in init pydantic.__init__
        File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
            # +--- init= parameter
    ImportError: cannot import name dataclass_transform
```

There is a singular difference though, previously it was:
```
File "/root/.local/lib/python3.9/site-packages/inflect/__init__.py", line 76, in <module>
```

and now it is:
```
File "/usr/local/lib/python3.9/site-packages/inflect/__init__.py", line 76, in <module>
```

**Comment by reconman** [comment]
If I start the script manually in the Tautulli container, it works.

But if I start the script via the Tautulli Notification Agent interface, the error above happens.

I'm a bit stuck atm.

**Comment by DJScias** [comment]
Hello there,

Noticed that the https://github.com/RickDB/PlexAniSync/compare/154-import-error branch got updated again with https://github.com/RickDB/PlexAniSync/commit/310057c959b727b3a5d4c6e4abda42b99f13191b.

After I re-created the Docker with that latest commit, everything seems back in order:
```
Tautulli Notifiers :: Script error:
    2022-10-28 15:10:20 PlexAniSync - version: 1.3.19
    2022-10-28 15:10:20 Updating single show: Tate no Yuusha no Nariagari
    2022-10-28 15:10:20 [MAPPING] Custom mapping found locally, using: custom_mappings.yaml
    2022-10-28 15:10:20 [MAPPING] Adding remote mapping url: https://raw.githubusercontent.com/RickDB/PlexAniSync-Custom-Mappings/main/series-tvdb.en.yaml
[...]
2022-10-28 15:10:28 --------------------------------------------------
    2022-10-28 15:10:28 [ANILIST] Used custom mapping | title: Tate no Yuusha no Nariagari | season: 1 | anilist id: 99263
    2022-10-28 15:10:28 [ANILIST] Updating series: The Rising of the Shield Hero | Episodes watched: 25
    2022-10-28 15:10:28 [ANILIST] Found AniList entry for Plex title: Tate no Yuusha no Nariagari
    2022-10-28 15:10:28 [ANILIST] Series is already marked as completed on AniList so skipping update
    2022-10-28 15:10:28 [ANILIST] Used custom mapping | title: Tate no Yuusha no Nariagari | season: 2 | anilist id: 111321
    2022-10-28 15:10:28 [ANILIST] Updating series: The Rising of the Shield Hero Season 2 | Episodes watched: 2
    2022-10-28 15:10:28 [ANILIST] Found AniList entry for Plex title: Tate no Yuusha no Nariagari
    2022-10-28 15:10:28 [ANILIST] Series year did not match however skip year check was given so adding anyway => Plex has 2018 and AniList has 2022
    2022-10-28 15:10:28 [ANILIST] Plex episode watch count [2] was higher than the one on AniList [1] which has total of 13 episodes | updating AniList entry to CURRENT
    2022-10-28 15:10:28 Plex to AniList sync finished
```

When I checked my AniList afterwards the episode count had been successfully changed from 1 to 2.

**Comment by reconman** [comment]
I noticed that the library causing the error was added with an update of inflect, so I reverted it.

Wanted to write something but then I had to lie down because of a cold.

I'll merge the branch soon.

**Comment by DJScias** [comment]
> I noticed that the library causing the error was added with an update of inflect, so I reverted it.
> 
> Wanted to write something but then I had to lie down because of a cold.
> 
> I'll merge the branch soon.

Thank you for your work so far!

My best wishes on you getting better.
