### ISSUE TITLE
v1.3.22 - continual sync errors

### ISSUE THREAD

**Issue by Raptor2213** [RickDB/PlexAniSync#186]
After upgrading from 1.3.21 to .22, sync keeps failing when it reaches the sync limit for "too many requests".

2023-03-23 23:40:58 [GRAPHQL] log_error - https://graphql.anilist.co: 429 Client Error: Too Many Requests for url: https://graphql.anilist.co/
2023-03-23 23:40:58 [GRAPHQL] Response header: CF-RAY: 7acc3d35085de82f-DFW
2023-03-23 23:40:58 [GRAPHQL] Response header: Connection: keep-alive
2023-03-23 23:40:58 [GRAPHQL] Response header: Content-Length: 74
2023-03-23 23:40:58 [GRAPHQL] Response header: Content-Type: application/json
2023-03-23 23:40:58 [GRAPHQL] Response header: Date: Fri, 24 Mar 2023 04:40:58 GMT
2023-03-23 23:40:58 [GRAPHQL] Response header: NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
2023-03-23 23:40:58 [GRAPHQL] Response header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0xu0v74WtqDYOQlBTjWuuqkT8ywx5joLUuRpRYKcrjZm1RcGh27tpPnhUXvpLHSa6i623doEOthhtQg0nM7k8yrc4HY0VgsoQS1kih%2BMjuqQhtkjVoaYTiv9CkqiMTGdfBPh%2Fw%3D%3D"}],"group":"cf-nel","max_age":604800}
2023-03-23 23:40:58 [GRAPHQL] Response header: Retry-After: 60
2023-03-23 23:40:58 [GRAPHQL] Response header: Server: cloudflare
2023-03-23 23:40:58 [GRAPHQL] Response header: Vary: Accept-Encoding
2023-03-23 23:40:58 [GRAPHQL] Response [application/json]:
{"data": null,"errors": [{"message": "Too Many Requests.","status": 429}]}
2023-03-23 23:40:58 [GRAPHQL] GraphQL query failed with 1 errors
2023-03-23 23:40:58 [GRAPHQL] Error #0:
2023-03-23 23:40:58 [GRAPHQL]    | Too Many Requests.
Traceback (most recent call last):
  File "C:\Program Files\PlexAniSync\PlexAniSync.py", line 106, in <module>
    start()
  File "C:\Program Files\PlexAniSync\PlexAniSync.py", line 100, in start
    anilist.match_to_plex(anilist_series, plex_series_watched)
  File "C:\Program Files\PlexAniSync\plexanisync\anilist.py", line 253, in match_to_plex
    media_id_search = self.__find_id_season_best_match(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PlexAniSync\plexanisync\anilist.py", line 370, in __find_id_season_best_match
    matches = self.graphql.search_by_name(title)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PlexAniSync\plexanisync\graphql.py", line 93, in search_by_name
    media = (operation + data).page.media
             ~~~~~~~~~~^~~~~~
  File "C:\Users\Liandri\AppData\Local\Programs\Python\Python311\Lib\site-packages\sgqlc\operation\__init__.py", line 2510, in __add__
    raise ex
sgqlc.operation.GraphQLErrors: Too Many Requests.

**Comment by reconman** [comment]
Sorry, didn't test the "too many requests" behavior, I've added a test to make sure this error is caught in the future.

**Comment by dGstone18** [comment]
@reconman Any chance a settings variable could be added for a custom rate limit? Or seconds (sleeps) between requests? I'm seeing consistent rate limit errors every run.
