### ISSUE TITLE
[PLEX] Unable to authenticate to Plex Media Server

### ISSUE THREAD

**Issue by ogkimra** [RickDB/PlexAniSync#196]
```
C:\Users\KIRA\Downloads\PlexAniSync-master>python PlexAniSync.py
2023-04-30 10:13:41 PlexAniSync - version: 1.3.25
2023-04-30 10:13:41 [MAPPING] Custom map file not found: custom_mappings.yaml
2023-04-30 10:13:41 [ANILIST] Retrieving AniList list for user: isoni
2023-04-30 10:13:43 [ANILIST] Found 165 anime series on list
2023-04-30 10:13:44 [PLEX] Unable to authenticate to Plex Media Server
Traceback (most recent call last):
  File "C:\Users\KIRA\Downloads\PlexAniSync-master\plexanisync\plexmodule.py", line 73, in __authenticate
    plex = PlexServer(base_url, token, session)
  File "C:\Users\KIRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\plexapi\server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "C:\Users\KIRA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\plexapi\server.py", line 751, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://127.0.0.1:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

**Comment by Soitora** [comment]
Are you using Direct Authentication (Plex Token) or myPlex?

**Comment by reconman** [comment]
Already solved via Discord. Authentication was set to direct instead of myplex.
