### ISSUE TITLE
Plex Anime Library is too big to handle all the watched Animes?

### ISSUE THREAD

**Issue by KaiserBh** [RickDB/PlexAniSync#20]
I think I got a huge library of animes in My Plex that it can't handle the watched episodes? tried to increase the timeout for the session but no luck if you can help me figure out a solution that will be great, also it could be a unique problem for me only, so I have got around 1070 animes in my plex library it was working fine with 300 animes after increasing the library started getting this error. 

```prolog
2020-03-02 00:58:07 [PLEX] Found 1070 anime series in section: Animes
2020-03-02 00:58:07 [PLEX] Retrieving watch count for series
Traceback (most recent call last):
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\PlexAniSync.py", line 156, in <module>
    start()
  File ".\PlexAniSync.py", line 140, in start
    plex_anime_series)
  File "C:\Users\Black\Desktop\PlexAniSync-master\PlexAniSync-master\plexmodule.py", line 160, in get_watched_shows
    for episode in show.episodes():
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\video.py", line 357, in episodes
    return self.fetchItems(key, **kwargs)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\base.py", line 148, in fetchItems
    data = self._server.query(ekey)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\server.py", line 376, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Black\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
I was thinking maybe add delay for each request? that could be a potential fix but do let me know if you found a solution I will try to debug it and see if I can find a solution.

**Comment by RickDB** [comment]
The error suggest some sort of connection issue, would try to run from a different machine or check firewall rules just in case.

Still could be Plex Media Server throttling it although looking over the code now don't see where as we fetch all shows as a whole (plex.library.section()) to memory and locally interpret watched state.
Modified plexmodule.py below which adds a 5ms delay between episode requests and 15ms delay between shows so we can check for any throttling:

https://gist.github.com/RickDB/7bd90e2d5ba2115b7708145275f56076

**Comment by KaiserBh** [comment]
Thank you, just checked it and it seem that was the problem most likely a firewall issue, since I was trying to run off my local PC but my server is like at different country, so running it locally with the same pc that is running the plex server seem to solve the issue. 
Gonna just close this.

**Comment by KaiserBh** [comment]
Thank you, just checked it and it seem that was the problem most likely a firewall issue, since I was trying to run off my local PC but my server is like at different country, so running it locally with the same pc that is running the plex server seem to solve the issue. 
Gonna just close this.
