### ISSUE TITLE
TautulliSyncHelper.py error

### ISSUE THREAD

**Issue by BlayZin** [RickDB/PlexAniSync#25]
Since the recent updates I get this error when the script gets started:

```
Tautulli Notifiers :: Script error:
    2020-04-29 21:04:03 [MAPPING] Custom map file not found: custom_mappings.ini
    2020-04-29 21:04:03 Updating single show: Legend of the Galactic Heroes
    2020-04-29 21:04:08 [ANILIST] Retrieving AniList list for user: BlayZin
    2020-04-29 21:04:09 [ANILIST] Found 491 anime series on list
    2020-04-29 21:04:09 [PLEX] Retrieving anime series from section: Anime
    2020-04-29 21:04:09 [PLEX] Found 141 anime series in section: Anime
    2020-04-29 21:04:09 [PLEX] Found matching anime series
    2020-04-29 21:04:09 [PLEX] Retrieving watch count for series
    2020-04-29 21:04:09 [PLEX] Found 1 watched series
    2020-04-29 21:04:09 [ANILIST] Matching Plex series to Anilist
    Traceback (most recent call last):
        File "/opt/PlexAniSync/TautulliSyncHelper.py", line 145, in <module>
            start()
        File "/opt/PlexAniSync/TautulliSyncHelper.py", line 138, in start
            plex_series_watched)
        File "/opt/PlexAniSync/anilist.py", line 530, in match_to_plex
            potential_titles = potential_titles_cleaned.copy()
    AttributeError: 'list' object has no attribute 'copy' 
```

**Comment by RickDB** [comment]
Tautulli is still using Python 2 which explains that error, will add a fix for this in a sec :)

**Comment by RickDB** [comment]
Should be fixed now and updating docker images in a sec.

**Comment by BlayZin** [comment]
it works now.
