### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by katekyonni** [RickDB/PlexAniSync#58]
Hi, I just updated my docker container to the version released today (latest Tag)

My log is now full of these errors:

```
2021-03-14 22:50:31 [PLEX] Error occured during episode processing of show <Show:109556:100-man-no-Inochi-no>

Traceback (most recent call last):

  File "/plexanisync/plexmodule.py", line 190, in get_watched_shows

    season_watchcount = get_watched_episodes_for_show_season(season)

  File "/plexanisync/plexmodule.py", line 276, in get_watched_episodes_for_show_season

    watched_episodes_of_season = [e for e in season.episodes() if e.isWatched]

  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 686, in episodes

    return self.fetchItems(key, Episode, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 205, in fetchItems

    items = self.findItems(data, cls, ekey, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 227, in findItems

    item = self._buildItemOrNone(elem, cls, initpath)

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 98, in _buildItemOrNone

    return self._buildItem(elem, cls, initpath)

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 83, in _buildItem

    return cls(self._server, elem, initpath, parent=self)

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 53, in __init__

    self._loadData(data)

  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 833, in _loadData

    if self.skipParent and not self.parentRatingKey:

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 402, in __getattribute__

    self.reload()

  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 285, in reload

    self._loadData(data[0])

  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 835, in _loadData

    if self.parentThumb.startswith('/library/metadata/'):

AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by reconman** [comment]
I think it's related to an incorrect bugfix for https://github.com/pkkid/python-plexapi/issues/655. If you enable seasons, does the error disappear?

**Comment by katekyonni** [comment]
Yes the errors are gone if seasons are enabled.
Thank you! :)

**Comment by reconman** [comment]
Wait, you are the one who reported the initial bug. Can you tell the dev that it didn't work and post the new error log?
